# ./github/workflows/deploy.yml

name: Deploy Middleman to GH Pages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tech-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: ./tech-docs

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Node packages cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm install

      - name: Build Middleman
        run: |
          bundle exec middleman build --clean

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tech-docs/build
          allow_empty_commit: true
