name: Deploy Middleman to GH Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tech-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./tech-docs

      - name: Build Middleman
        run: |
          bundle exec middleman build --clean --verbose

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tech-docs/build
          allow_empty_commit: true
